import StyledComponentsRegistry from "@/registry";
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
const inter = Inter({
    subsets: ['latin'],
    weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: 'My Home Exchange',
  description: 'Generated by create next app',
}

// https://stackoverflow.com/questions/75337953/what-causes-nextjs-warning-extra-attributes-from-the-server-data-new-gr-c-s-c
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
          suppressHydrationWarning={true}
          className={inter.className}
      >
      <StyledComponentsRegistry>
        {children}
      </StyledComponentsRegistry>
      </body>
    </html>
  )
}
